#version 460
#define LOCAL_SZ_X 1024
layout(push_constant) uniform pushBlock {
      int total;      
};

layout(binding = 0) readonly buffer buf1 { float X[]; };

layout(binding = 1) writeonly buffer buf2 {  float Y[]; };

layout(local_size_x = LOCAL_SZ_X, local_size_y = 1, local_size_z = 1) in;

void main()
{
    for (int i = int(gl_GlobalInvocationID.x); i < total; i += int(gl_NumWorkGroups.x * gl_WorkGroupSize.x))
    {
        Y[i] = log(X[i]);
    }
}