#version 460
layout(push_constant) uniform pushblock {
    uint total;
};
layout(binding=0) readonly buffer buf1 { float X[]; };
layout(binding=1) readonly buffer buf2 { float W[]; };
layout(binding=2) writeonly buffer buf3 { float Y[]; };
layout(local_size_x = 1024, local_size_y = 1, local_size_z=1) in;

void main(){
    for(uint i = gl_GlobalInvocationID.x; i < total; i += gl_NumWorkGroups.x * gl_WorkGroupSize.x){
        Y[i] = X[i] + W[i];        
    }
}